### ISSUE TITLE
Pod-UI receives MIDI but can not send MIDI to POD 2.0

### ISSUE THREAD

**Issue by acepukas** [arteme/pod-ui#1]
Just tried out pod-ui on Arch linux. As the title says I can't send commands to the POD but if I manipulate the POD manually, I see that manipulation reflected in the pod-ui app.

I've reset the POD to factory settings to rule out any edits I've made potentially causing problems. The MIDI connection cable I am using is an M-Audio midisport UNO MIDI to USB adapter. Unfortunately I don't have plain MIDI cables to test with at the moment.

When I open the MIDI connection selection interface within pod-ui, even if I select the midisport UNO (the correct MIDI ports in this case) the "Test" button fails. The read out from the test says

    Test failed:
    panic

The "Autodetect" button returns the same thing.

Regardless of the test outcome, I can still connect to the POD and see changes made to the POD within pod-ui so I know that at least one line of communication is open, from POD to computer.

However, I can't get communication from computer to POD working with one strange exception. If I reset the POD and then select a preset and then edit it, then set the POD back into manual mode, then try to select the edited preset from pod-ui it will always set the POD to preset 1:A but always 1:A, no matter which preset I've selected. So there is some kind of connection back to the POD but it's not working as intended on my system.

**Comment by arteme** [comment]
Hi!
I'm so glad to hear from a fellow POD user, even in these unfortunate circumstances when your experience with the app is less than stellar. The general issue of being able to change controls but not detect the device or get the programs dump from it points to the MIDI cable (cheap USB-MIDI cables are known for not supporting SysEx messages that are used for detection and patch store/load commands), but the **M-Audio midisport UNO** is one of those actually recommended by Line6 support themselves on the Line6 forums for being known to work. Of course, Linux is not on their radar and our experience may differ, but the device is known to work on Windows. I've just actually ordered one of those off Thoman last night as the Terratec USB sound card I use is not exactly mobile.

I'm not quite sure, what's going on with the program select either, but once the program is modified in pod-ui, when you switch to it, the program will be loaded to the edit buffer using a SysEx message. This is also how Line6 Edit does it. I wonder if the problen is --once again-- the SysEx. I've noticed that sending random SysEx very fast gets my device confused and for me it always switched to program `3:A`.

To try to get to the bottom if this, I would suggest trying to send a couple SysEx messages from the command line. First start `amidi` in receive mode in the terminal:
```
arteme ~ $ amidi --list-devices
Dir Device    Name
IO  hw:1,0,0  PHASE 26 USB(16/48) MIDI 1
arteme ~ $ amidi -p hw:1,0,0 -d
``` 
Then, open another terminal window and send a device inquiry message:
```
amidi -p hw:1,0,0 -S "F0 7E 7F 06 01 F7"
```
Then, let's send a edit buffer data dump request:
```
amidi -p hw:1,0,0 -S "F0 00 01 0C 01 00 01 F7"
```

At this point, there's gotta be some output in the first window. If you could post that here, it may shed some light on what is going on.

This is the reply from my device:
```
F07E7F060200010C0000000330323230F7
F000010C01010100000000000001000000000001000100010000010A030E0206020D03000107030F000603000000010A07040000070F0000000000000000000003000C000000000000000000020D0000020900000000010502000301030F000D000F000000000000000A0F0000000007040000000C070405060E0605060D07090200060F060602000704060806050200050307040601F7
```

**Comment by acepukas** [comment]
Here's the breakdown of those commands on my system:

    amidi --list-devices

    Dir Device    Name
    ...
    IO  hw:4,0,0  USB Uno MIDI Interface MIDI 1
    ...

With amidi in receive mode I ran the following in another terminal:

    amidi -p hw:4,0,0 -S "F0 7E 7F 06 01 F7"

Output:

    F07E7F0602002008630E500220313235F7
    F07E7F060200010C0000000330323330F7

Then ran:

    amidi -p hw:4,0,0 -S "F0 00 01 0C 01 00 01 F7"

Output:


F000010C0101010000000001000100000000000100000001000101090109010C0203010B0000010101050102060702010709000007040000000000000000000003000C000000000003000C00020D020D0200020000010200020002000200010F000A0200000A020200000000000008080000000000000000000000000000000000000000000000000000000000000000000000000000F7

**Comment by arteme** [comment]
Thank you for the dump. By the look of it, you have more than one MIDI device attached and I did not account for that :laughing: 
It's an "Evolution Synthesis" device that replies first, for which pod-ui is completely unprepared for. The edit buffer dump looks okay and is of the correct length, so there's no problem with SysEx using your cable.

Another thing not implemented yet is setting the MIDI channel. My POD is in the "omni" mode, which means that it will comply with PC/CC MIDI messages on any channel. `pod-ui` uses channel 1 to send the messages and does not differentiate between channels when it receives messages.

If you want to experiment, you can disconnect the Evolution Synthesis device and set the POD to channel 1 or "omni mode" (press "MIDI" and scroll all the way to "A"). In the meantime I will make changes for pod-ui to recognize multiple devices and send/listen using the correct MIDI channel.

**Comment by acepukas** [comment]
Ok we have progress. Putting the POD in "omni mode" allowed for two-way communication.

I'm not sure what "Evolution Synthesis" is. That might be my audio interface, which has MIDI I/O ports, identifying itself as something similar.

I disconnected all midi devices except for the POD but that didn't seem to make a difference. Only "omni mode" did.

I imagine broadcasting MIDI commands on "omni mode" might conflict with other apps/hardware listening on specific channels? I don't know enough about MIDI to say.

The reason I was looking for something to control the POD with is because certain settings seem to only be available through MIDI manipulation. Specifically I was looking to set the minimum value for the volume pedal and the min and max frequency of the wah pedal. Now that I've had the chance to change those values with pod-ui, I'm not sure that I'm getting the effect that I wanted.

With the volume pedal for example, it seems to be stuck with a range of around 75% to 100%. Changing the minimum value for the volume pedal via pod-ui didn't seem to affect the range at all. I don't know if that's an issue with pod-ui or I'm just misunderstanding how the pedals are supposed to work. I've seen claims of being able to calibrate pedals on later models of the POD so that the pedal ranges can be changed but I haven't seen anything like that for the POD 2.0 specifically.

I've gone over the manual but didn't find anything related to those settings other than the MIDI control messages appendix which is kinda what led me here.

**Comment by arteme** [comment]
With the latest commits I fixed POD detection when there are multiple MIDI devices. I also added a "MIDI channel" input and added channel auto-detect logic. I've build an AppImage if you'd like to give it a go: https://github.com/arteme/pod-ui/releases/download/the-next-best-thing/Pod-UI-v0.4.0-6-g695aa1a-x86_64.AppImage

As far as your problem with the volume pedal goes, I'm not sure what's going on. I dug out my floorboard and tried with this latest version. For me setting volume lower works correctly. Setting it to 0% I can get the volume all the way off with the volume pedal and setting it to 50% lets me set the volume in about 50..100% range with the pedal.

**Comment by acepukas** [comment]
Hi Artem,

Tried out the new app image and it's easier to work with now. The POD was
auto detected right away. The "autodetect" and "test" routines from the
config interface both worked as well.

Thanks for your help :)

As for the pedal range adjustment, that still is not working for me. There
might be something wrong with my POD. Maybe it's a firmware bug. From the
POD manual I have it says that the current firmware revision is "G". I
tried searching for information on what revisions exist for the POD 2.0 but
it's pretty hard to find. The joys of working with ancient hardware. I'll
have to ask around on the line6 forum.

Thanks again!

**Comment by acepukas** [comment]
Just want to add that I found a way to calibrate my floorboard. Apparently the only way to do it is to open it up and make adjustments right on the pedal sensor circuit with a small dial. I must have a really early model of that floorboard because it just didn't respond to the min and max values set via MIDI. The firmware on my POD is version 2.3 so it doesn't get more up to date than that as far as the POD 2.0 goes. In any case your app was helpful because I could just make the adjustments I needed and test the pedal's response by watching the how it reacts within the pod-ui interface.

**Comment by arteme** [comment]
Thank you so much for your testing and input. I'm glad you found this project useful!
