### ISSUE TITLE
Feature request: automatically loading patch from POD 2.0

### ISSUE THREAD

**Issue by MidnightRetro** [arteme/pod-ui#34]
When I click on a patch number on Pod-ui, it switches the POD 2.0 to that patch, BUT it doesn't load the patch into the editor, requiring to press the “load patch” button. I find this very confusing. It would be better if pressing a patch number would switch it on the Pod AND load its parameters into the editor at the same time.

**Comment by thiswastheonlyavailableusername** [comment]
I am using a cheap USB to MIDI interface that I bought just to test your program 😁
Anyway, winrt version solved the problem

**Comment by arteme** [comment]
Awesome. Just one more question, if you don't mind me asking - what device do you have? Does it have a brand / model, or maybe a link to a web shop? I'm curious because I have a couple cheap USB-MIDI cables myself that do not work, so it's always good to know what to recommend when people ask.

**Comment by thiswastheonlyavailableusername** [comment]
![IMG_20230419_151023760-01~2.jpeg](https://user-images.githubusercontent.com/28755229/233127166-f286bc6e-89b3-433f-a501-2d34e3f3819a.jpeg)

It's called BMUSB100 by Bespeco
