### ISSUE TITLE
USB MIDI POD 2.0

### ISSUE THREAD

**Issue by rogeriods** [arteme/pod-ui#49]
Hi!
I'm Rogério from Brazil.
I would like to know if there is some trick to work with my MIDI USB cable.
I tried reverse in out | out in and won't work.
Here my cable model and I'm using Win 11 PRO last version of RUST.
![MIDI](https://github.com/arteme/pod-ui/assets/21225828/50ee234a-d467-4ae3-8e56-523f9d89a53d)

**Comment by arteme** [comment]
Dear Rogèrio,

I'm afraid I have bad news for you -- I have the same one and it doesn't work for me :( Ironically, I bought it specifically for my POD 2.0.

When I say, it doesn't work, I mean that the SysEx messages do not go through. Unfortunately, this is a common issue with the cheap Chinese USB-MIDI cables. SysEx messages are long and complex and I don't know if it is a buffering issue or a timing issue, and whether it is a hardware problem or a driver problem, but SysEx messages just don't go though...

Without the SysEx messages, the device is not going to be detected and you won't be able to send or receive patches to/from the POD. You can still switch presets and change individual controls though.

If you can get a hold of M-Audio MIDISport Uno or Bespeco BMUSB100, these USB-MIDI dongles are known to work correctly. Also Roland UM-ONE MK2, iConnectivity mio, MOTU FastLane USB are said to be good, but I've no personal experiences with these.

**Comment by arteme** [comment]
On Windows you may also try the winrt build (If you're running from sources, `cargo run -F winrt`), which may have better support for the cable. It helped with Bespeco USB-MIDI cable: https://github.com/arteme/pod-ui/issues/34

**Comment by arteme** [comment]
Added a page describing this in more detail: https://arteme.github.io/pod-ui/pages/usb-midi-cables.html
