### ISSUE TITLE
PODxt Live - MIDI cable MacOS DOREMI with SysEx?

### ISSUE THREAD

**Issue by ccastroneves** [arteme/pod-ui#53]
Dear all,
I recently bought a MIDI cable that supposedly had SysEx connectivity (I read all your info beforehand). Well... tried connecting my PODxt Live to my MacOS and nothing. The blue light turns on, but nothing. Am I doing something wrong? I'm running a Macbook Pro M1 Pro with Sonoma.
![IMG_3768](https://github.com/arteme/pod-ui/assets/166151842/4698ba35-429b-4288-859d-d2f88d9d38cb)

**Comment by arteme** [comment]
Dear @ccastroneves,

By the looks of it, this is a Doremidi MTU-11 cable. I've never tried a Doremidi cable, but by a quick search, it seems like they have a range MIDI products, so I would think they have it together. Let's think, what can be happening.

1. Does your Mac recognize the device? Do the MIDI ports show up in the pod-ui settings dialog?
2. Have you connected the POD XT correctly? The MIDI cables have IN/OUT and the POD has IN/OUT, I can never remember, which goes where. Cable IN to device IN, or cable IN to device OUT -- have you tried both?
3. Assuming the ports are recognized and the device is correctly connected, if you run pod-ui and manually select the correct ports and device type. When you change any controls on the POD like "Bass" or "Treble", does the app react in any way?
4. POD XT devices have a USB port. Would you be able to try connecting the POD to your Mac using USB? Are there any chances to run drivers written for Intel Mac or Apple silicone?

**Comment by ccastroneves** [comment]
Thanks for the response. It hadn't recognized anything, until now that I tried opening logic (for whatever reason).
So now it appears to have some sort of connection, but it doesn't recognize the sounds on the PodXt live. Check out the attached pictures.

![IMG_3802](https://github.com/arteme/pod-ui/assets/166151842/e15b256f-09e4-49e9-85da-bfdf7dab9845)
![IMG_3803](https://github.com/arteme/pod-ui/assets/166151842/6b81a7aa-fafb-40ba-85d2-03f783743d0a)
![IMG_3804](https://github.com/arteme/pod-ui/assets/166151842/a6a08043-4c83-4ccb-8c04-60499ca61d09)

**Comment by ccastroneves** [comment]
This is the actual link to the cable:https://www.doremidi.shop/products/doremidi-midi-to-usb-c-type-c-cable-usb-midi-converter-with-indicator-light-for-macbook-android?spm=..collection_38e473af-fe8e-4fd7-9fed-1d621e86d44b.collection_detail_1.3&spm_prev=..product_62f34c13-03bf-4823-9b76-5557cfa4727d.header_1.1

**Comment by ccastroneves** [comment]
I'm laughing my ass off... Because I'm ridiculous! Thanks to you question and to DOREMIDI's website, I inverted the midi cables... In to out, and out to in. There you go! lol. Works perfectly!

**Comment by arteme** [comment]
All's well that ends well! :)
