### ISSUE TITLE
Saving POD presets to computer disk

### ISSUE THREAD

**Issue by BJ-Chico** [arteme/pod-ui#58]
Is there a way to save the tones to a computer's hard disk  after editing OR to download and save the originals as a backup copy?...

**Comment by arteme** [comment]
Hi! Unfortunately, not yet. I've not had nearly enough time to work on this lately :(

**Comment by M1DHB** [comment]
You can use Line6 Edit if you can get it.
I have a copy of 3.06 installer and can share a link here:-
https://drive.google.com/file/d/1fnORJNt0OGPJLLOYcxm_82ZyelUw8Ufq/view?usp=drive_link

**Comment by BJ-Chico** [comment]
I have Line 6 Edit BUT it doesn't give me an option to save my POD 2.0   tones to disk....

**Comment by M1DHB** [comment]
Line 6 Edit has built in Help.
See also these images.
![L6Edit-SelectionGet-savesToneJPG](https://github.com/user-attachments/assets/49c6b5f5-39b3-4bb9-a888-342f80dc30dd)
![L6Edit-TransferSaveBackupBundle](https://github.com/user-attachments/assets/2e0ec93b-e279-4ae1-ac27-f7786ed2bcfd)

**Comment by BJ-Chico** [comment]
Thanks all ... finally got L6edit to work and connect.

regards,
-bj-
